INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Gabon','GA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Guyana','GY',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Guyane française','GF',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Guinea','GM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bailiwick of Guernsey','GG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Guadeloupe','GP',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Guatemala','GT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Guam','GU',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Grenada','GD',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Greece','GR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Greenland','GL',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Guinea','GN',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Guinea-Bissau','GW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Namibia','NA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Nauru','NR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Nigeria','NG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Australian External Territories ','AQ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('South Sudan','SS',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('South Africa','ZA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Netherlands','NL',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Nepal','NP',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Norway','NO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Norfolk Islands','NF',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('New Zealand','NZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('New Caledonia','NC',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Niue','NU',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Niger','NE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Nicaragua','NI',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Denmark','DK',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Dominica','DM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Dominican Rep.','DO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Germany','DE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Timor-Leste','TL',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Diego Garcia','IO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Lao P.D.R.','LA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Liberia','LR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Latvia','LV',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Russian Federation','RU',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Lebanon','LB',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Lesotho','LS',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Romania','RO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Luxembourg','LU',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Rwanda','RW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Libya','LY',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('French Departments and','RE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Territories in the Indian','LT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Ocean','LI',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Madagascar','MG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Martinique','MQ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Marshall Islands (Kwajalein)','MH',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Mayotte','YT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Macao','MO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Macedonia','MK',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Malawi','MW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Malaysia','MY',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Mali','ML',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Isle of Man','IM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Mexico','MX',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Monaco','MC',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Morocco','MA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Mauritius','MU',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Mauritania','MR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Mozambique','MZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Montenegro','ME',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Montserrat','MS',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Moldova','MD',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Maldives','MV',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Malta','MT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Mongolia','MN',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('United States','US',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Myanmar','MM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Micronesia','FM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Vanuatu','VU',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bahrain','BH',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Barbados','BB',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Vatican','VA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bahamas','BS',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bangladesh','BD',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bermuda','BM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('United States Virgin Islands','VI',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('British Virgin Islands','VG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Benin','BJ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Venezuela','VE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Belgium','BE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Belarus','BY',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Belize','BZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bonaire','BQ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bosnia and Herzegovina','BA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Botswana','BW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bolivia','BO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Burundi','BI',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Burkina Faso','BF',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bhutan','BT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Northern Marianas','MP',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Bulgaria','BG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Brazil','BR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Brunei Darussalam','BN',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Samoa','WS',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Saudi Arabia','SA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Cyprus','CY',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('San Marino','SM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Sao Tome and Principe','ST',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Saint Pierre and Miquelon','PM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Senegal','SN',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Serbia','RS',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Seychelles','SC',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Saint Lucia','LC',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Saint Vincent and the','VC',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Saint Kitts and Nevis','KN',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Saint Helena','SH',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Somalia','SO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Solomon Islands','SB',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Sudan','SD',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Suriname','SR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Sri Lanka','LK',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Swaziland','SZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Sweden','SE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Switzerland','CH',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Spain','ES',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Slovakia','SK',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Slovenia','SI',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Syrian Arab Republic','SY',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Sierra Leone','SL',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Sint Maarten','SX',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('United Arab Emirates','AE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Aruba','AW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Armenia','AM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Argentina','AR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('American Samoa','AS',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Iceland','IS',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Haiti','HT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Ireland','IE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Azerbaijan','AZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Afghanistan','AF',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Andorra','AD',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Alaska','AK',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Albania','AL',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Algeria','DZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Angola','AO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Antigua and Barbuda','AG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Anguilla','AI',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Eritrea','ER',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Estonia','EE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Ecuador','EC',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Ethiopia','ET',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('El Salvador','SV',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('United Kingdom','GB',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Yemen','YE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Oman','OM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Australia','AU',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Austria','AT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Honduras','HN',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Landskapet Aland','AX',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Jordan','JO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Uganda','UG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Uruguay','UY',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Uzbekistan','UZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Ukraine','UA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Wallis and Futuna','WF',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Iraq','IQ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Iran','IR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Israel','IL',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Egypt','EG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Italy','IT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('India','IN',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Indonesia','ID',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Japan','JP',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Jamaica','JM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Zambia','ZM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Jersey','JE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Equatorial Guinea','GQ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Georgia','GE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('China','CN',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Central African Rep.','CF',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Djibouti','DJ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Gibraltar','GI',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Zimbabwe','ZW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Chad','TD',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Czech Rep.','CZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Chile','CL',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Cameroon','CM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Cape Verde','CV',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Kazakhstan','KZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Qatar','QA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Cataloina','ES',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Canada','CA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Kenya','KE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Cayman Islands','KY',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Comoros','KM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Costa Rica','CR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Cocos Islands','CC',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Colombia','CO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Congo','CG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Dem. Rep. of the Congo','CD',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Cuba','CU',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Kuwait','KW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Cook Islands','CK',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Curaçao','CW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Croatia','HR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Christmas Islands','CX',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Kyrgyzstan','KG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Kiribati','KI',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Taiwan','TW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Tajikistan','TJ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Tanzania','TZ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Turks and Caicos Islands','TC',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Turkey','TR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Tonga','TG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Tokelau','TK',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Tonga','TO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Turkmenistan','TM',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Tuvalu','TV',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Tunisia','TN',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Trinidad and Tobago','TT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Panama','PA',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Paraguay','PY',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Pakistan','PK',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Papua New Guinea','PG',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Palau','PW',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Palestinian','PS',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Faroe Islands','FO',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Peru','PE',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Portugal','PT',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Falkland Islands','FK',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Poland','PL',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('French Polynesia','PF',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Puerto Rico','PR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('France','FR',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Fiji','FJ',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Finland','FI',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Philippines','PH',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Hungary','HU',1,1,1);
INSERT INTO main.countries (name, iso_code,region_id,currency_id,lang_id) VALUES ('Hong Kong','HK',1,1,1);

