module.exports.REFUND_OPTION = {
  FULL_CHARGE: 'FULL_CHARGE',
  APPLY_CANCELLATION_POLICY: 'APPLY_CANCELLATION_POLICY',
  APPLY_CANCELLATION_POLICY_IGNORE_DATE: 'APPLY_CANCELLATION_POLICY_IGNORE_DATE',
  FULL_REFUND: 'FULL_REFUND',
  REMOVE_PAX: 'REMOVE_PAX',
  CUSTOM: 'CUSTOM',
}
